config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memory.urls')),
    path('accounts/',include('accounts.urls')),
]
from django.conf.urls.static import static
from django.conf import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memory/urls.py
from django.urls import path
from .views import *   # views.py 내의 모든 객체, 함수 포함
from django.contrib.auth import views as auth_views

app_name = 'memory'

urlpatterns = [
    path('', intro, name='main'),

    path('contactAddress', contact, name='Memories_ContactAddress'),
    path('addcreate/', create_address, name='addcreate'),
    path('adddetail/<int:pk>',DetailAddress.as_view(),name='adddetail'),
    path('addupdate/<int:pk>',UpdateAddress.as_view(),name='addupdate'),
    path('adddelete/<int:pk>', DeleteAddress.as_view(), name='adddelete'),

    path('point', point, name='point'),
    path('pocreate/',create_point, name='pocreate'),

    path('mocreate/',create_money, name='mocreate'),

    path('schedule', schedule, name='schedule'),
    path('sccreate/', create_schedule, name='sccreate'),
    path('scdetail/<int:pk>',DetailSchedule.as_view(),name='scdetail'),
    path('scupdate/<int:pk>', UpdateSchedule.as_view(), name='scupdate'),
    path('scdelete/<int:pk>', DeleteSchedule.as_view(), name='scdelete'),

    path('event', event, name='event'),
    path('calendar', calendar, name='calendar'),
]

memory/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_addcon')
    name = models.CharField(max_length=200)
    work = models.CharField(max_length=200)
    mail = models.EmailField()
    tel = models.CharField(max_length=200)
    memo = models.CharField(max_length=200)
    birth = models.DateField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('memory:address_detail', args=[str(self.id)])

class Schedule(models.Model):
    user2 = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_sche')
    title = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    date = models.DateField()
    memo = models.TextField()
    anniversary = models.CharField(max_length=200) #초대받은사람


    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user2.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('memory:schedule', args=[str(self.id)])

class Point(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_point')
    point = models.IntegerField()
    date = models.DateField()
    #sender = models.ForeignKey(Address.name,on_delete=models.CASCADE)
    #receiver = models.ForeignKey(Address.name,on_delete=models.CASCADE)
    sender = models.CharField(max_length=200)
    receiver = models.CharField(max_length=200)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('memory:point', args=[str(self.id)])


class Money(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_money')
    money = models.IntegerField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('memory:point', args=[str(self.id)])

memory/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Schedule, Address, Point, Money


class ScheduleForm(forms.ModelForm):
    title = forms.CharField(label='제목 ')
    date = forms.DateField(label='일정 ')
    place = forms.CharField(label='장소 ')
    memo = forms.CharField(label='내용 ', widget=forms.Textarea)
    anniversary = forms.CharField(label='초대받은 사람 ')

    class Meta:
        model = Schedule
        fields = ["title", "date", "place", "memo", "anniversary"]


class AddressForm(forms.ModelForm):
    name = forms.CharField(label='이름 ')
    tel = forms.CharField(label='연락처 ')
    work = forms.CharField(label='소속 ')
    mail = forms.CharField(label='이메일 ')
    birth = forms.DateField(label='생일 ')
    memo = forms.CharField(label='메모 ', widget=forms.Textarea)

    class Meta:
        model = Address
        fields = ["name", "tel", "work", "mail", "birth", "memo"]


class PointForm(forms.ModelForm):
    point = forms.IntegerField(label='포인트 ')
    date = forms.DateField(label='날짜 ')
    sender = forms.CharField(label='보낸사람 ')
    receiver = forms.CharField(label='받는사람 ')

    class Meta:
        model = Point
        fields = ["point", "date", "sender", "receiver"]


class MoneyForm(forms.ModelForm):
    money = forms.IntegerField(show_hidden_initial=True)

    class Meta:
        model = Money
        fields=["money"]

memory/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .models import Address, Schedule, Point, Money
from django.contrib.auth.models import User
from .forms import ScheduleForm, AddressForm,PointForm, MoneyForm

def intro(request):
    pass
    return render(request, 'memory/main.html')

def contact(request):
    address = Address.objects.filter(user=request.user).order_by('name')
    return render(request,'memory/Memories_ContactAddress.html',{'address':address})

def create_address(request):
    user_obj = User.objects.get(username=request.user.get_username())
    if request.method == 'POST':
        address_form = AddressForm(request.POST)
        if address_form.is_valid():
            new_address = address_form.save(commit=False)
            new_address.user = user_obj
            new_address.save()
            return redirect('memory:Memories_ContactAddress')
    else:
        address_form = AddressForm()
    return render(request, 'memory/address_create.html',{'form':address_form})

class DetailAddress(DetailView):
    model = Address
    template_name_suffix = '_detail'

class UpdateAddress(UpdateView):
    model = Address
    fields = ['name','tel','work','mail','birth','memo']
    template_name_suffix = '_update'
    success_url = reverse_lazy('memory:Memories_ContactAddress')

class DeleteAddress(DeleteView):
    model = Address
    fields = ['name','tel','work','mail','birth','memo']
    template_name_suffix = '_delete'
    success_url = reverse_lazy('memory:Memories_ContactAddress')

def point(request):
    point = Point.objects.filter(user=request.user)
    money = Money.objects.filter(user=request.user)
    return render(request, 'memory/point.html',{'point':point,'money':money})

def create_point(request):
    user_obj = User.objects.get(username=request.user.get_username())
    if request.method == 'POST':
        point_form = PointForm(request.POST)
        if point_form.is_valid():
            new_point = point_form.save(commit=False)
            new_point.user = user_obj
            new_point.save()
            return redirect('memory:point')
    else:
        point_form = PointForm()
    return render(request, 'memory/point_create.html',{'form':point_form})

def create_money(request):
    user_obj = User.objects.get(username=request.user.get_username())
    if request.method == 'POST':
        money_form = MoneyForm(request.POST)
        if money_form.is_valid():
            new_money = money_form.save(commit=False)
            new_money.user = user_obj
            new_money.save()
            return redirect('memory:point')
    else:
        money_form = MoneyForm()
    return render(request, 'memory/money_create.html',{'form':money_form})


def schedule(request):
    schedule = Schedule.objects.filter(user2=request.user)
    return render(request, 'memory/schedule.html',{'schedule':schedule})


def calendar(request):
    schedule = Schedule.objects.filter(user2=request.user)
    return  render(request, 'memory/calendar.html',{'schedule':schedule})


def create_schedule(request):
    user_obj = User.objects.get(username=request.user.get_username())
    if request.method == 'POST':
        schedule_form = ScheduleForm(request.POST)
        if schedule_form.is_valid():
            new_schedule = schedule_form.save(commit=False)
            new_schedule.user2 = user_obj
            new_schedule.save()
            return redirect('memory:schedule')
    else:
        schedule_form = ScheduleForm()
    return render(request, 'memory/schedule_create.html',{'form':schedule_form})


class UpdateSchedule(UpdateView):
    model = Schedule
    fields = ['title','place','date','memo','anniversary']
    template_name_suffix = '_update'
    success_url = reverse_lazy('memory:schedule')

class DeleteSchedule(DeleteView):
    model = Schedule
    fields = ['title','place','date','memo','anniversary']
    template_name_suffix = '_delete'
    success_url = reverse_lazy('memory:schedule')

class DetailSchedule(DetailView):
    model = Schedule
    template_name_suffix = '_detail'

def event(request):
    pass
    return  render(request, 'memory/event.html')

memory/templates/memory/Memories_ContactAddress.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<div id="address_" style="height:822px;">
			<h3>■ address</h3>
			<input type="search" id="searchname" placeholder="검색" />
			<input type="button" value="검색" id="searchbtn"/>
			<div class="address_submenu">
				<ul>
					<li><a href="#ㄱ">ㄱ</a></li>
					<li><a href="#ㄴ">ㄴ</a></li>
					<li><a href="#ㄷ">ㄷ</a></li>
					<li><a href="#ㄹ">ㄹ</a></li>
					<li><a href="#ㅁ">ㅁ</a></li>
					<li><a href="#ㅂ">ㅂ</a></li>
					<li><a href="#ㅅ">ㅅ</a></li>
					<li><a href="#ㅇ">ㅇ</a></li>
					<li><a href="#ㅈ">ㅈ</a></li>
					<li><a href="#ㅊ">ㅊ</a></li>
					<li><a href="#ㅋ">ㅋ</a></li>
					<li><a href="#ㅌ">ㅌ</a></li>
					<li><a href="#ㅍ">ㅍ</a></li>
					<li><a href="#ㅎ">ㅎ</a></li>
					<li><a href="#&">&</a></li>
				</ul>
			</div>
			<div class="add">
				<a href="addcreate">+ 연락처 추가</a>
			</div>

			<div class="address_contents">
				<div id="ㄱ" class="move">전체</div>

				{% for add in address %}

				<div class="contents">
					<div class="people">
						<a href="{% url 'memory:adddetail' add.id %}">{{ add.name }}</a>
					</div>
				</div>
				{% endfor %}
				<!--<div id="ㄴ" class="move">ㄴ</div>
					<div class="contents">
						<div class="people">
							<a href="#">나란히</a>
						</div>
					</div>

				<div id="ㄷ" class="move">ㄷ</div>
					<div class="contents">
						<div class="people">
							<a href="#">다람쥐</a>
						</div>
					</div>
					
				<div id="ㄹ" class="move">ㄹ</div>
				<div id="ㅁ" class="move">ㅁ</div>
				<div id="ㅂ" class="move">ㅂ</div>
				<div id="ㅅ" class="move">ㅅ</div>
				<div id="ㅇ" class="move">ㅇ</div>
				<div id="ㅈ" class="move">ㅈ</div>
				<div id="ㅊ" class="move">ㅊ</div>
				<div id="ㅋ" class="move">ㅋ</div>
				<div id="ㅌ" class="move">ㅌ</div>
				<div id="ㅍ" class="move">ㅍ</div>
				<div id="ㅎ" class="move">ㅎ</div>
				<div id="&" class="move">&</div>-->
			</div>

		</div>
		<div class="clear"></div>
{% endblock %}

memory/templates/memory/address_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div id="address_edit" style="height:811px;">
			<div class="add_prev">■ 연락처 추가</div>
			<div class="add_picture">
				<div class="picture"><img src="{% static 'image\icon\add_picture.png' %}" alt="사용자이미지"/></div><br>
			</div>
			<div class="add_contents">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}
				<!--<p class="title">이름</p><input type="text" name="name" />
				<p class="title">연락처</p><input type="tel" name="address" />
				<p class="title">소속</p><input type="text" name="belong" />
				<p class="title">이메일</p><input type="email" name="belong" />
				<p class="title">생일</p><input type="date" name="birthday" />
				<p class="title">메모</p><textarea id="textbox" name="memo" cols="100" rows="5"></textarea>-->
				<br>
				<input type="submit" id="save" value="추가하기"/>
				</form>
			</div>
		</div>
		<div class="clear"></div>


{% endblock %}

memory/templates/memory/address_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<div id="address_add">
			<div class="add_prev"><a href="{% url 'memory:Memories_ContactAddress' %}"> < 이전으로</a></div>
			<div class="add_picture">
				<div class="picture"><img src="{% static 'image\icon\add_picture.png' %}" alt="사용자이미지"/></div><br>
				<ul class="audit">
					<li><a href="{% url 'memory:addupdate' object.id %}"><img src="{% static 'image\icon\addit.png' %}" alt="수정"/></a></li>
					<li><a href="{% url 'memory:adddelete' object.id %}" class="delete"><img src="{% static 'image\icon\trash.png' %}" alt="삭제"/></a></li>
				</ul>
			</div>
			<div class="add_contents">
				<p class="title">이름</p><p>{{ object.name }}</p>
				<p class="title">연락처</p><p>{{ object.tel }}</p>
				<p class="title">소속</p><p>{{ object.work }}</p>
				<p class="title">이메일</p><p>{{ object.mail }}</p>
				<p class="title">생일</p><p>{{ object.birth }}</p>
				<p class="title">메모</p><p>{{ object.memo }}</p>
			</div>
		</div>
		<div class="clear"></div>
		
{% endblock %}

memory/templates/memory/address_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<div id="address_edit">
			<div class="add_prev">■ 연락처 수정</div>
			<div class="add_picture">
				<div class="picture"><img src="{% static 'image\icon\add_picture.png' %}" alt="사용자이미지"/></div><br>
			</div>
			<div class="add_contents">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}
				<!--<p class="title">이름</p><input type="text" name="name" />
				<p class="title">연락처</p><input type="tel" name="address" />
				<p class="title">소속</p><input type="text" name="belong" />
				<p class="title">이메일</p><input type="email" name="belong" />
				<p class="title">생일</p><input type="date" name="birthday" />
				<p class="title">메모</p><textarea id="textbox" name="memo" cols="100" rows="5"></textarea>-->
				<br>
				<input type="submit" id="save" value="저장하기"/>
				</form>
			</div>
		</div>
		<div class="clear"></div>
{% endblock %}

memory/templates/memory/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script>
		$(document).ready(function(){

			//달력 script문
			var cYear = new Date().getFullYear();	//현재
			var cMonth = new Date().getMonth();
			var cDate = new Date().getDate();
			var now = new Date().getDay();
			var dd = $("td");	//td 42개

			var cal = function(){
				$("#year").html(cYear);

				$("#month").html(cMonth+1);

				for(var i=0; i<42; i++)
					dd.eq(i).html("&nbsp");	//달력 전체 공백 초기화

				var startIndex = new Date(cYear, cMonth, 1).getDay(); //5	//현재달의 시작 일
				var monLength = 32 - new Date(cYear, cMonth, 32).getDate(); //31	//몇일까지 있는지?
				var date = 1;
				for(var i=startIndex; i<monLength+startIndex; i++){
					date = date + 1;
					dd.eq(i).html(date-1);
				}
				dd.eq(cDate+startIndex-1).addClass('ddeq');

				$("#today").html(cYear + '.' + (cMonth+1) + '.' + cDate);
			};

			cal();

			$("#prev").click(function(){
				cYear = new Date(cYear, cMonth-1, cDate).getFullYear();
				cMonth = new Date(cYear, cMonth-1, cDate).getMonth();
				cal(cYear, cMonth);

				for(var i=0;i<45;i++)
					dd.eq(i).removeClass('ddeq');

				return false;
			});
			$("#next").click(function(){
				cYear = new Date(cYear, cMonth+1, cDate).getFullYear();
				cMonth = new Date(cYear, cMonth+1, cDate).getMonth();
				cal(cYear, cMonth);

				for(var i=0;i<45;i++)
					dd.eq(i).removeClass('ddeq');

				return false;
			});

		});
	</script>

		<div id="calendar" style="height:1000px;">
			<div class="month_bar">
				<caption>
					<span id="year"></span><br>
					<a href="#" id="prev"><img id="il" width="40px"src="{% static 'image\btn\prev.png' %}" alt="이전달"/></a>
					<span id="month"></span>
					<a href="#" id="next"><img id="ir" width="40x" src="{% static 'image\btn\next.png' %}" alt="다음달"/></a>
				</caption>
			</div>
			<div class="add">
				<a href="{% url 'memory:sccreate' %}">+ 일정추가</a>
			</div>
			<table class="calheader" >
					<th>SUN</th><th>MON</th><th>TUE</th><th>WED</th>
					<th>THU</th><th>FRI</th><th>SAT</th>
			</table>
			<table class="calbody" border="1" >
					<tr class="date">
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
						<tr>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
							<td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td><td align="left" valign="top">&nbsp;</td>
						</tr>
					</tr>
			</table>


		</div>
		<br><br>
		<div class="clear"></div>

{% endblock %}

memory/templates/memory/event.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div id="events"style="height:1200px;">
<br><br>
			<div class="imageslides">
				<img src="{% static 'image\slideimage\eventslide.png' %}" alt="imageslide(1)"/>
			</div>
			<br><br><br>
			<div class="mo">
			<h3 id="mo" >모금함 </h3><h3>4 </h3><h3>개</h3>
			</div>

			<div class="ev_con">
				<div >
					<a href="https://happybean.naver.com/donations/H000000157090"><img src="{% static 'image\slideimage\1.png' %}"/></a>

				</div>
				<div class="eventcontent">
					<a href="https://happybean.naver.com/donations/H000000157140"><img src="{% static 'image\slideimage\2.png' %}"/></a>

				</div>
				<div class="eventcontent">
					<a href="https://happybean.naver.com/donations/H000000156503"><img src="{% static 'image\slideimage\3.png' %}"/></a>

				</div>
				<div class="eventcontent">
					<a href="https://happybean.naver.com/donations/H000000156471"><img src="{% static 'image\slideimage\4.png' %}"/></a>

				</div>
			</div>
		</div>
		<br><br><br>
		<div class="clear"></div>
		
{% endblock %}

memory/templates/memory/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		<div class="imageslide" >
			<img src="{% static 'image\slideimage\image(2).jpg' %}" alt="imageslide(1)"/>
		</div>
		<div class="clear"></div>

		<div class="content" style="height:340px;">
			<br><br><br>
			<a href=schedule >
				<div id="schedule" class="image_btn">
					<img src="{% static 'image\icon\cal.png' %}" alt="schedule" />
					<h4>스케줄 관리</h4>
					<p>하루 일정을 보여주는 메모리즈 캘린더를 사용하면 <br>효율적인 일정관리를 할 수 있습니다.</p>
				</div>
			</a>

			<a href=contactAddress>
				<div id="address" class="image_btn">
					<img src="{% static 'image\icon\book.png' %}" alt="address" />
					<h4>연락처 관리</h4>
					<p>소중한 사람들의 연락처를 등록하여  <br>효율적인 일정관리를 할 수 있습니다.</p>
				</div>
			</a>

			<a href=point>
				<div id="pointt" class="image_btn">
					<img src="{% static 'image\icon\point3.png' %}" alt="point" />
					<h4>포인트 관리</h4>
					<p>포인트를 통하여 소중한 사람들 또는 <br>어려운 이웃에게 기부를 할 수 있습니다.</p>
				</div>
			</a>
		</div>
		<br><br><br/>
		<div class="clear"></div>

{% endblock %}

memory/templates/memory/money_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
	label{visibility:hidden; margin:-30px;}
	input:nth-child(2){float:left;}
</style>
		<div id="point2" style="height:842px;">
			<div class="schedule">■ 포인트 충전하기</div>		
			<div class="point_table">
				<table>
					<tr>
						<th>no</th>
						<th>충전할 금액</th>
						<th>내용</th>
						<th>비고</th>
					</tr>
					<tr>
						<form action="" method="post" enctype="multipart/form-data" id="moneyform">
							<td><a href="#">01</a></td>
							{% csrf_token %}
							<td>{{ form.as_p }}원</td>
							<td><a href="#">포인트 충전</a></td>
							<td><input type="submit" value="충전하기" id="sub"></td>
						</form>
					</tr>
				</table>
			</div>
		<div class="clear"></div>
		</div>
{% endblock %}

memory/templates/memory/point.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
   $(document).ready(function(){
   var sum =0;

	{% for mo in money %}
		sum += {{mo.money}}
	{% endfor %}

      $(".point_bold").html(sum);
   });
</script>
		
		<div id="point" style="height:762px;">
			<div class="schedule" >■ 포인트 관리</div>
			<p class="coin_add"><a href="mocreate">+ 충전하기</a></p>
			<p class="coin_add"><a href="pocreate">+ 선물추가하기</a></p>
			<div class="point_table">
				<table>
					<tr>
						<th>no</th>
						<th>포인트</th>
						<th>보낸 사람</th>
						<th>받는 사람</th>
						<th>날짜</th>
					</tr>
					{% for po in point %}
					<tr>
						<td><a href="#">{{ po.id }}</a></td>
						<td><a href="#">{{ po.point }}원</a></td>
						<td><a href="#">{{ po.receiver }}</a></td>
						<td><a href="#">{{ po.sender }}</a> </td>
						<td>{{ po.date }}</td>
					</tr>
					{% endfor %}

				</table>
				<div class="point_coin">
					<p>충전 포인트</p>

					<p class="point_bold">

					</p><p> 원</p>

				</div>
			</div>
		</div>
		<div class="clear"></div>
		
{% endblock %}

memory/templates/memory/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

		<div id="schedules" style="height:811px;">
			<div class="schedule">■ 스케줄 관리</div>
			<div class="schedule_add"><a href="sccreate">+ 스케줄 추가</a></div>
			<div class="schedule_table">
				<table>
					<tr>
						<th>no</th>
						<th>제목</th>
						<th>내용</th>
						<th>날짜</th>
					</tr>
					{% for sc in schedule %}
					<tr>
						<td><a href="{% url 'memory:scdetail' sc.id %}">{{ sc.id }}</a></td>
						<td><a href="{% url 'memory:scdetail' sc.id %}">{{ sc.title }}</a></td>
						<td><a href="{% url 'memory:scdetail' sc.id %}">{{ sc.memo }}</a></td>
						<td>{{ sc.date }}</td>
					</tr>
					{% endfor %}
				</table>
			</div>

		</div>
		<div class="clear"></div>

{% endblock %}

memory/templates/memory/schedule_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<div id="schedule_look">
			<div class="schedule_look">■ 스케줄 확인</div>
			<hr>
			<p class="title_look">{{ object.title }}</p>
			<hr><br>
			<p class="schedule_title"> 일정 : </p><p class="schedule_startday">{{ object.date }}</p><p class="schedule_endday">~ {{ object.date }}</p><br>
			<p class="schedule_title">장소 : </p><p class="schedule_place">{{ object.place }}</p><br>
			<p class="schedule_title">내용 : </p><p class="schedule_memo">{{ object.memo }}</p><br>

			<a href="{% url 'memory:schedule' %}"><button type="button" class="schedule_action">확인</button></a>
			<a href="{% url 'memory:scupdate' object.id %}"><button type="button" class="schedule_edit">수정</button></a>
			<a href="{% url 'memory:scdelete' object.id %}"><button type="button" class="schedule_edit">삭제</button></a>
		</div>
		<div class="clear"></div>
		
		<div id="schedule_modal">
			<div class="body">
				<p>스케줄을<br>삭제하시겠습니까?</p>
				<form action="" method="post">
					{% csrf_token %}
				<input type="submit" id="confirm" value="확인"><button type="button" id="cancel" onclick="location.href='{% url 'memory:scdetail' object.id %}'">취소</button>
				</form>
			</div>
		</div>
{% endblock %}